import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hiraya Pathway Training Center",
  description: "Generated by Hiraya Pathway Training Center",
  icons: {
  icon: [
    { url: "/favicon.ico", type: "image/x-icon" },
    { url: "/img/HIRAYA.png", sizes: "32x32", type: "image/png" },
  ],
  apple: "/img/HIRAYA.png",
  shortcut: "/favicon.ico",
}

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
        <Navbar />
        <div>{children}</div>
        <Footer />
        <PopupWidget />
      </ThemeProvider>
      </body>
    </html>
  );
}
